-- Initial data with Features prioritized in M-SPLearning implementation:
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (1, false, false, true, 'Pedagogical', 'A', null);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (2, false, false, true, 'Content Management', null, 1);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (3, false, false, true, 'Educational Activities', null, 1);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (4, false, false, true, 'Interactivity', null, 1);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (5, false, false, true, 'Multimedia Resources', null, 1);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (6, false, false, true, 'Usability', 'A', null);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (7, false, false, true, 'Accessibility', null, 6);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (8, false, false, true, 'Attractiveness', null, 6);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (9, false, false, true, 'Intelligibility', null, 6);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (10, false, false, true, 'Learnability', null, 6);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (11, false, false, true, 'Operability', null, 6);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (12, false, false, true, 'Compatibility', 'A', null);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (13, false, false, true, 'Coexistence', null, 12);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (14, false, false, true, 'Interoperability', null, 12);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (15, false, false, true, 'Security', 'A', null);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (16, false, false, false, 'Accountablility', null, 15);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (17, false, false, false, 'Authenticity', null, 15);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (18, false, false, false, 'Confidentiality', null, 15);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (19, false, false, true, 'Integrity', null, 15);
INSERT INTO tb_feature (id, abstract, hidden, mandatory, name, operator, id_parent) VALUES (20, false, false, true, 'Reliability', null, 15);