//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.msplearning.android.compatibility.interoperability;

import com.msplearning.entity.Student;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.FormHttpMessageConverter;
import org.springframework.http.converter.json.GsonHttpMessageConverter;
import org.springframework.web.client.RestTemplate;

public class StudentRESTfulClient_
    implements StudentRESTfulClient
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public StudentRESTfulClient_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new FormHttpMessageConverter());
        restTemplate.getMessageConverters().add(new GsonHttpMessageConverter());
        rootUrl = "http://10.0.2.2:8080/restful-app";
    }

    @Override
    public Student insert(Student student) {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Student> requestEntity = new HttpEntity<Student>(student, httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/insert/student/"), HttpMethod.POST, requestEntity, Student.class).getBody();
    }

}
